-- Migration 009: Migrate existing work_plan and clarification_history from
-- separate risks/questions_for_reviewer fields to a single concerns array.
--
-- SQLite's JSON functions do not support the complex nested SELECT required
-- for an in-place UPDATE of arbitrary JSON blobs.  The original approach used
-- app-layer normalization on read, but the database was reset after this
-- migration was introduced so no legacy records exist.  The normalization
-- helpers have been removed.
